Studio/Models/Links.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Studio.Models
{
	public class Links
	{
		[Key]
		public int ID { get; set; }

		//public int? LinkCategoryID { get; set; }
		[Required(ErrorMessage = "必填"), MaxLength(100)]
		public string LinkUrl { get; set; }
		[Required(ErrorMessage = "必填")]
		public int? SortOrder { get; set; }
		[Required(ErrorMessage = "必填"), MaxLength(100)]
		public string Name { get; set; }

		public string PictureFile { get; set; }

		public string Description { get; set; }

		public string Contact { get; set; }

		public string Email { get; set; }

		public DateTime? DateCreated { get; set; }

		//public string UpdateUser { get; set; }
	}
}

Studio/Areas/Admin/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Studio.Services;
using Studio.Models.Others;
using Studio.Models;

namespace Studio.Areas.Admin.Controllers
{
    public class LinksController : Controller
    {
        //
        // GET: /Admin/Links/

        public ActionResult Index(int? page)
        {
			var links = new SiteHelp().GetLinks();
			var model = new Paginated<Links>(links, page ?? 1, 20);

			return View(model);
        }

		public ActionResult Add()
		{
			var link = new Links();
			link.SortOrder = 0;

			return View(link);
		}

		[HttpPost]
		public ActionResult Add(Links links)
		{
			if (ModelState.IsValid)
			{
				var obj = new SiteHelp().InsertLink(links);
				if (obj.Tag <= 0)
				{
					ViewBag.Error = obj.Message;
					return View(links);
				}

				return RedirectToAction("Index");
			}

			return View(links);
		}

		public ActionResult Edit(int id)
		{
			var link = new SiteHelp().GetLink(id);

			return View(link);
		}

		[HttpPost]
		public ActionResult Edit(Links links)
		{
			if (ModelState.IsValid)
			{
				var obj = new SiteHelp().UpdateLink(links);
				if (obj.Tag <= 0)
				{
					ViewBag.Error = obj.Message;
					return View(links);
				}

				return RedirectToAction("Index");
			}

			return View(links);
		}

		public ActionResult Delete(int id)
		{
			var obj = new SiteHelp().DeleteLink(id);
			if (obj.Tag <= 0)
			{
				ViewBag.Error = obj.Message;
			}
			return RedirectToAction("Index");
		}

    }
}

Studio/Areas/Admin/Views/Links/Add.cshtml
@{
	ViewBag.Title = "Add";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>增加友情链接</h2>
@using (Html.BeginForm("Add", "Links", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.Partial("_LinkForm")

	<div class="section">
		<span style="color: Red;">@ViewBag.Error</span>
		<button type="submit" class="button-save">提交</button>
	</div>
}

Studio/Areas/Admin/Views/Links/Edit.cshtml
@model Studio.Models.Links
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>编辑友情链接</h2>
@using (Html.BeginForm("Edit", "Links", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.Partial("_LinkForm")
	@Html.HiddenFor(m => m.ID)
	<div class="section">
		<span style="color: Red;">@ViewBag.Error</span>
		<button type="submit" class="button-save">提交</button>
	</div>
}

Studio/Areas/Admin/Views/Links/Index.cshtml
@model Studio.Models.Others.Paginated<Studio.Models.Links>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>友情链接</h2>
<p>
    <a href="/Admin/Links/Add" class="button-add">添加友情链接</a>
</p>

<table class="grid">
	<tr>
		<th>
			#
		</th>
		<th>
			名称
		</th>
		<th>
			添加时间
		</th>
		<th>
			链接网站
		</th>
		<th>
			联系人邮箱/QQ
		</th>
		<th>
			排序
		</th>
		<th>
		</th>
	</tr>
	@foreach (var item in Model)
 {
	 <tr>
		<td>@item.ID</td>
		<td>@item.Name</td>
		<td>@item.DateCreated</td>
		<td><a href="@item.LinkUrl" target="_blank">@item.LinkUrl</a></td>
		<td>
			@item.Email
		</td>
		<td>
			@item.SortOrder
		</td>
		<td>
			<a href="/Admin/Links/Edit/@item.ID" class="button-edit">编辑</a>
			<a href="/Admin/Links/Delete/@item.ID" class="button-delete delete">删除</a>
		</td>
	 </tr>
 }
 </table>
 @Model.Pager("pager")

Studio/Areas/Admin/Views/Links/_LinkForm.cshtml
@model Studio.Models.Links
		   
<div class="section">
	<div class="section-header">
		<h3>名称</h3>
	</div>
	<div class="section-body">
		<div class="row">
			@Html.TextBoxFor(m => m.Name, new { @class = "title" }) <cite>*</cite>
			@Html.ValidationMessageFor(m => m.Name)
		</div>
	</div>
</div>
<div class="section">
	<div class="section-header">
		<h3>链接</h3>
	</div>
	<div class="section-body">
		<div class="row">
			@Html.TextBoxFor(m => m.LinkUrl, new { @class = "large" }) <cite>*</cite>
			@Html.ValidationMessageFor(m => m.LinkUrl)
		</div>
	</div>
</div>
<div class="section">
	<div class="section-header">
		<h3>联系人</h3>
	</div>
	<div class="section-body">
		<div class="row">
			@Html.TextBoxFor(m => m.Contact, new { @class = "large" })
			@Html.ValidationMessageFor(m => m.Contact)
		</div>
	</div>
</div>
<div class="section">
	<div class="section-header">
		<h3>联系方式</h3>
	</div>
	<div class="section-body">
		<div class="row">
			@Html.TextBoxFor(m => m.Email, new { @class ="large"})
			@Html.ValidationMessageFor(m => m.Email)
		</div>
	</div>
</div>
<div class="section">
	<div class="section-header">
		<h3>排序</h3>
	</div>
	<div class="section-body">
		<div class="row">
			@Html.TextBoxFor(m => m.SortOrder) <cite>*</cite>
			@Html.ValidationMessageFor(m => m.SortOrder)
		</div>
	</div>
</div>
<div class="section">
	<div class="section-header">
		<h3>备注</h3>
	</div>
	<div class="section-body">
		<div class="row">
			@Html.TextAreaFor(m => m.Description)
			@Html.ValidationMessageFor(m => m.Description)
		</div>
	</div>
</div>